### ISSUE TITLE
NullPointerException while querying Bnd dependency source containers

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1694] opened 2017-04-26 19:25 UTC
While developing Bndtools I saw this error being logged. Though I can't describe the steps to reproduce the stack trace might help to solve the issue.

> Error querying Bnd dependency source containers.

```
java.lang.NullPointerException
	at bndtools.central.Central.toPath(Central.java:385)
	at bndtools.launch.BndDependencySourceContainer.createSourceContainers(BndDependencySourceContainer.java:93)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.getSourceContainers(CompositeSourceContainer.java:133)
	at org.eclipse.debug.core.sourcelookup.containers.CompositeSourceContainer.findSourceElements(CompositeSourceContainer.java:48)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupParticipant.findSourceElements(AbstractSourceLookupParticipant.java:70)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:142)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:505)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:785)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:344)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:741)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by bjhargrave** [comment] 2017-04-26 20:30
The issue is that `runbundle.getFile()` can return null. There are code paths through the repos where the null is passed as a success value to the DownloadBlocker.

The promise is resolved with null:

https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java#L130
https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java#L138-L142

Later a then operation on the promise calls success on the download blocker with the null file value:
https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java#L390-L401

Finally the container returns the null file value from the dowbload blocker.
https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Container.java#L83

So I think the fix is to change the then operation on the promise to check the promise value and it null, call failure instead of success on the download listener.

Ultimately, it would be better to replace DownloadBlockers with Promises, but thats a larger issue :-)

**Comment by bjhargrave** [comment] 2017-04-26 20:32
Or the Container can check for null in https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Container.java#L83 and return a fake File object with the error like https://github.com/bndtools/bnd/blob/master/biz.aQute.bndlib/src/aQute/bnd/build/Container.java#L88.

**Comment by bjhargrave** [comment] 2017-04-27 00:54
I merged https://github.com/bndtools/bnd/issues/2021 so hopefully this fixes the issue.

**Comment by bjhargrave** [comment] 2017-05-12 16:12
Closing. If it is still a problem, please open a new issue.

**Closed by bjhargrave** 2017-05-12 16:12 UTC
