### ISSUE TITLE
Using "Run As -> Bnd OSGi Test Launcher (JUnit)" from a project fails when there are sources not containing tests

### ISSUE THREAD

**Issue by tomq42** [bndtools/bndtools#1557] opened 2016-09-29 17:01 UTC
Create an OSGi enroute project with a "*.test" name.
Put a number of source files in the project, some containing tests, some not. 
I quite often have utility code within my test project, base classes for the tests and so on.
Select the project and select "Run As -> Bnd OSGi Test Launcher (JUnit)".

You get a "no runnable methods" error from junit for source files that don't contain junit tests, regardless of their names.

You get the same just selecting a package.

If you select "Run As -> Bnd OSGi Test Launcher (JUnit)" from the .bnd file, you get a different behaviour. Here it runs the tests listed in the bnd file, meaning it only runs those source files that end with the name "Test" (which is also mighty confusing, and caused me _huge_ confusion for a good period one day, but that's another issue).

Having selected only one source file to run the tests from, the only ways back to running all the tests is to either select the project/package, or to delete the run configuration. Since selecting the package/project doesn't work in this circumstance, the only option is to delete the run configuration.

**Comment by bjhargrave** [comment] 2016-09-29 17:03
I do not see this issue doing run on my test project. I will note it is using Junit 3 so perhaps Junit 4 tests have this issue.

**Comment by tomq42** [comment] 2016-09-29 17:09
I am certainly using junit 4 with annotations.

**Comment by gamerson** [comment] 2016-12-16 16:41
hey @tomq42  I can't reproduce this with the latest Bndtools 3.3.0.  Can you share an example github repo that has this problem?

**Comment by gamerson** [comment] 2016-12-20 17:15
Going to close this until more info about reproducing.  Thanks!

**Closed by gamerson** 2016-12-20 17:15 UTC
