### ISSUE TITLE
[3.0.0.DEV] New projects with sub-bundles not recognized in Workspace-Repository

### ISSUE THREAD

**Issue by lostiniceland** [bndtools/bndtools#1073] opened 2015-03-11 08:01 UTC
After I upgraded to 3.0.0.DEV I cannot create new BndTools projects using sub-bundles.

Even though the project generated the desired Jars, the sub-bundles are not recognized by the Workspace-Repository. Instead there is a "bundle" with the project-name which cannot be opened in jar-viewer because there is no jar with that name on the filesystem.

Projects created with 2.4.1 still working fine in 3.0.0.DEV.

Reproduce:
- Open former 2.4.1 workspace
- Create new BndTools project "test"
- Check "Use sub bundles"
- Save
- Create new Bundle-Descriptor "api"
- Create new Bundle-Descriptor "provider"
- Add some packages to the sub-bundles
- Check generated folder... test.api and test.provider have been created
- Check Repositories View...only "test" appears! Api and provider-bundle cannot be used in other projects!

**Comment by lostiniceland** [comment] 2015-03-11 09:02
The issue can be solved by creating a new cnf-project in another workspace and replacing the old one. Downloaded dependencies should be in a custom file-based OBR outside the workspace.

Is there a plan to provide some automatic migration?

**Comment by pkriens** [comment] 2015-06-01 16:20
The problem is that the Project is now more efficiently refreshed by the new builder but now we do not pick up the changes in the sub builders. I've change this to always calculate the sub bundle's bsns and versions. So the update will be in bnd. Keep open to verify

**Comment by pkriens** [comment] 2015-06-26 16:55
Seems to work now (still need get the editor to refresh this list but that is already another list). The subbundles now generate repo entries

**Closed by pkriens** 2015-06-26 16:55 UTC

**Comment by libliflin** [comment] 2015-10-28 13:59
When will this fix be rolled out to the update site?

Latest Mars from eclipse website
Latest Java 8 from sun website
Latest Bnd tools plugin from update site.
New workspace, switch to bndtools perspective
New Empty osgi project, default cnf
Enable sub bundles, save.
new bundle descriptor, new package, new class
new bundle descriptor, new package, new class
Repositories view: only one bundle will show under Workspace.
