### ISSUE TITLE
Source lookup fails in debugger

### ISSUE THREAD

**Issue by pkriens** [bndtools/bndtools#1395] opened 2016-06-08 06:36 UTC
It seems that source lookup recently got worse, though not sure.

My main hangup is that I can add the sources to the code on the -buildpath (in OSGI-OPT/src). I can then set a breakpoint but the frigging debugger cannot find them. 

I tried to add the Bnd container (as Java Library) but this crashes. We probably have to look into to add this container to the source lookup.

@gamerson something for you? It is a real pain in the ass ...

**Comment by gamerson** [comment] 2016-06-14 13:22
@pkriens is the debugger stopping? but the Eclipse sourcecode lookup is not loading the editor correctly? Could you share a sample setup that is easy to reproduce and I can take a look.

**Comment by lostiniceland** [comment] 2016-06-18 20:44
Not sure if this is related, but I had similar problems with provider-bundles. I code against the API and the resolver add the providers to -runbundles. Those bundles are not part of the Bnd-Container in Eclipse so the degugger will not open any class even though when I add the provider-source (if available in workspace).

My current workaround, is to create a boot-project where all run-files are stored. Within this project I add all bundles that I want to debug to the buildpath. Now I can debug the providers.

I was thinking of a fix for this: before launching, BndTools will add all remaining bundles which are inside runbundles but not in the buildpath to the Bnd-Container. Once the running instance is stopped, the Bnd-Container is resetted.

**Comment by gamerson** [comment] 2016-06-21 14:35
The problem seems to be if the project whose sources you are trying to debug that you have open in Eclipse, if its .classpath file has a src folder that uses a non-default output location, for example, in the following classpath file the first classpathentry of `kind="src"` specifies its output location instead of leaving it default location (which means just omit the output attribute).

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="aQute.bnd.classpath.container"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

In this situation the  `DefaultProjectClasspathEntry` that is used by JavaRuntime when computing the classpath of a JUnit launches, when it looks at java project reference from the BndContainer and in that Java project it finds a it finds a `non-default` output location then it tries to add it to the classpath as a eclipse folder source container not a java project source container.  See here:

![screen shot 2016-06-21 at 9 26 22 am](https://cloud.githubusercontent.com/assets/595221/16232976/50384198-3792-11e6-9df3-6c4076313aaa.png)

But if you modify the first classpathentry in the file to look like this (which is the way most eclipse projects are configured)
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="aQute.bnd.classpath.container"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

Then the computed source containers in launch source lookup will look like this:

![screen shot 2016-06-21 at 9 30 19 am](https://cloud.githubusercontent.com/assets/595221/16233109/cb6d9fca-3792-11e6-8a03-d99decd515fe.png)

So source lookup works as expected.

**Comment by bjhargrave** [comment] 2016-06-22 15:29
I am not sure I understand your pictures. What project is being debugged and what is the -buildpath of that project. Where are the entries for the project's aQute.bnd.classpath.container?

**Comment by gamerson** [comment] 2016-06-22 15:38
So in the bndtools.test workspace you can see there are two projects
test.debug
test.debug.dep

in the test.debug it does new Foo() where Foo comes from test.debug.dep.  So test.debug in its -buildpath has test.debug.dep

Now do a junit debug launch on the Test class and set a breakpoint at "new Foo()" and step into it.  You will notice that by default when you say "Debug as > JUnit" the launch, when it calculates the classpath it correctly sets everything up.  But however, the default Java Source Lookup when it encounters the test.debug.dep project, (that comes out of the BndContainer as a project reference) it doesn't add a 'ProjectContainer" but instead adds a "FolderContainer" (see the first screenshot) and thus the source lookup fails.  

In the 2nd screenshot after modifying the test.debug.dep/.classpath file (to remove the unnecessary output="bin" attribute), the Java Source Lookup correctly adds a "ProjectContainer" to the source lookup path (see second screenshot).

**Comment by gamerson** [comment] 2016-06-22 15:41
Actually what i just said is the case when you do "-buildpath: test.debug.dep;version=project"

Right now by default it does "-buildpath: test.debug.dep;version=latest", in this case it loads the generated jar in the classpath.  So the Java Source lookup loads the source from the generated jar (but it isn't editable).  It doesn't correctly find the project from source.  I didnt' include the screenshots from this case, sorry.

But either way, removing the output="bin" attribute fixes the problem in this case and the Foo class is correctly find in the original project and opens in an editable file in the java editor.

**Comment by bjhargrave** [comment] 2016-06-22 16:01
What is under the twisty for the highlighted project after the change to the .classpath?

**Comment by gamerson** [comment] 2016-06-22 19:48
So under the `test.debug` project it looks like this:

<img width="622" alt="screen shot 2016-06-22 at 2 43 01 pm" src="https://cloud.githubusercontent.com/assets/595221/16280958/b3e766f6-3887-11e6-8b50-71e5025c1497.png">

This looks the same before and after this fix.  This proposed change doesn't affect the BndContainer at all.  It is doing its job correctly.  The problem comes on the JUnit launch portion, when its building the classpath.  A combination of these two classes:

This class `org.eclipse.jdt.internal.launching.DefaultProjectClasspathEntry` and this method
`org.eclipse.jdt.launching.JavaRuntime.resolveOutputLocations(IJavaProject, int)` where its not doing the right thing when it sees custom output locations.

**Comment by pkriens** [comment] 2016-06-23 06:47
Could we detect this case in bndtools & then add a quick-fix? I already to some checking on the .classpath so we should be able to extend that

**Comment by gamerson** [comment] 2016-06-23 20:29
You mean in this class? `org.bndtools.builder.validate.ProjectPathsValidator`

**Comment by gamerson** [comment] 2016-06-23 21:08
@pkriens should this condition be an error or warning?  I can add a quick-fix either way.

**Comment by gamerson** [comment] 2016-06-24 06:47
For now I made it a warning.  See the proposed UI here: https://github.com/bndtools/bndtools/pull/1419

**Comment by pkriens** [comment] 2016-06-24 08:03
Agree, these things should be warning. Nice work!

**Comment by gamerson** [comment] 2016-06-24 15:01
See discussion here: https://github.com/bndtools/bndtools/pull/1419  There is a more proper fix that involves overriding the default standard Eclipse runtime classpath provider and providing our own so we can handle these source folder classpath entries more precisely, this is what m2e does.

**Closed** 2016-07-22 16:42 UTC
