### ISSUE TITLE
BUG 3.1 Final inkl. 1259 fix :  Downloading bundles through repositiory hangs without error log

### ISSUE THREAD

**Issue by flangel** [bndtools/bndtools#1250] opened 2015-12-15 10:59 UTC
3.1 RC2 

- issues is not RC2 specific 

Reproduce
========
1. go to BndHub Repository folder

2. Goto bndlib

3. Double click on 2.3.0 - Version opens successfully in tab

4. Double click on 2.4.0 --> Nothing happens

There is no error thrown. Nothing in ./.log file of eclipse. 
![nodownloadbundleissue](https://cloud.githubusercontent.com/assets/2772980/11808825/3d414778-a323-11e5-9ce3-22298c4190d3.png)

5. This problem can be reproduced for many different bundles in different repos.  I am not sure what it is, because there is log message anywhere. 

6. I can open same file in Browser successfully

Problem
=======
1. No error log of any kind generated
2. not working

**Comment by flangel** [comment] 2015-12-15 11:19
Allow an additional remark.

1. In the Build.bnd i reference the same bundle, and i get a tiny error message  

Description	Resource	Path	Location	Type
Unexpected jackson-core-asl;version='[1.9.8,1.9.9)',  error java.io.IOException: Downloading https://svn.xxxxxx/bundlerepo/jackson-core-asl/jackson-core-asl-1.9.8.jar failed and cache file /Users/flangel/.bnd/cache/https%3A%2F%2Fsvn.xxxx.de%2Fsvn%2Fcfn365%xxxxxxx-Cnf%2Ftrunk%2Fbundlerepo%2Fjackson-core-asl/jackson-core-asl-1.9.8.jar is not available or doesn't match the expected checksum, see log for details.

2. However, that's it. no more entries in any log

3. Its using this code https://github.com/bndtools/bnd/blob/master/biz.aQute.repository/src/aQute/bnd/deployer/repository/CachingUriResourceHandle.java

**Comment by flangel** [comment] 2015-12-15 12:49
doublechecked on two different MAC laptops. Same issues. Tried different networks. No differences, doesnt work

**Comment by flangel** [comment] 2015-12-16 09:31
Issue is caused by incorrect URL in BndHub. We used old BndHub URL

**Comment by flangel** [comment] 2015-12-16 11:43
Hello, 

need to reopen. Here the reproducable problem

Access to repos fails without error message
=================================
1. Create new example BndTools project in brand new workspace
1a. CNF project is created
1b. Example project is created
1c. BndTools Repository view shows all the repositories, access works

2. Gogo ext/repositories.bnd
2b. Replace with attached content
[repositories1.txt](https://github.com/bndtools/bndtools/files/63924/repositories1.txt)

3. New repositories show up
3a. Click on any amdatu bundle ==> Download/Opening FAILS
 

Problem
======
- Access to any bundle in Amdatu repositories fails

**Comment by flangel** [comment] 2015-12-16 11:44
Hello, 

need to reopen. Here the reproducable problem

Access to repos fails without error message
=================================
1. Create new example BndTools project in brand new workspace
1a. CNF project is created
1b. Example project is created
1c. BndTools Repository view shows all the repositories, access works

2. Gogo ext/repositories.bnd
2b. Replace with attached content
 
[repositories1.txt](https://github.com/bndtools/bndtools/files/63926/repositories1.txt)


3. New repositories show up
3a. Click on any amdatu bundle ==> Download/Opening FAILS
 

Problem
======
- Access to any bundle in Amdatu repositories fails

**Comment by flangel** [comment] 2015-12-18 17:47
Hi, this is a serious issue. Could someone confirm it ? We are experiencing it on many machines/users

**Comment by bjhargrave** [comment] 2015-12-18 19:24
Does this only happen with Amdatu repositories?

**Comment by flangel** [comment] 2015-12-21 09:37
let me try to find another public repo..

**Comment by flangel** [comment] 2015-12-21 16:08
Yes, it happens with our internal repos as well.

**Comment by bjhargrave** [comment] 2015-12-21 16:45
> Are you able to reproduce it with the Amdatu repos?

No, I haven't tried. I ask because there have been problems with Amdatu repos before: https://github.com/bndtools/bndtools/issues/1185.

**Comment by flangel** [comment] 2015-12-21 20:35
@bjhargrave , thanks for caring. do you have any other public repos I could try. I only have internal ones I cannot make available for testing.

**Comment by bjhargrave** [comment] 2015-12-21 21:28
Well there are the bnd repos: see the versions at https://dl.bintray.com/bnd/dist/ and the versions at https://dl.bintray.com/bndtools/bndtools/. All of these have index.xml.gz files under the version folders.

**Comment by bjhargrave** [comment] 2015-12-22 16:23
Please see #1259. Your problem may be the same.

I have made a test 3.1.1.DEV build at https://bndtools.ci.cloudbees.com/job/bndtools.next/lastSuccessfulBuild/artifact/build/generated/p2/ with the #1259 fix. Please try it out and report back if it fixes your issue.

**Comment by flangel** [comment] 2015-12-23 10:23
Hi, 

I was able to reproduce with 3.1 RC2 and get an error message using the dl.bintray repositories. 

See attached
Now trying the #1259 

 
![bndtoolsbug](https://cloud.githubusercontent.com/assets/2772980/11974783/a0fe519e-a967-11e5-8fbf-185806a25fe6.png)

**Comment by flangel** [comment] 2015-12-23 10:30
@bjhargrave : As discussed, i used the version you suggested to no avail. same error
![bndversion](https://cloud.githubusercontent.com/assets/2772980/11974871/8be23fae-a968-11e5-9356-d37db44eead3.png)

**Comment by bjhargrave** [comment] 2015-12-23 15:25
This seems to have been caused by https://github.com/bndtools/bndtools/commit/524b99b1ce43ae6a06fe098b4ea24298bdd726e0 which moved the `viewer.refresh()` off the UI thread. @lostiniceland Can you please look at a fix for this since you made the above commit?

**Closed** 2015-12-23 15:58 UTC

**Comment by bjhargrave** [comment] 2015-12-23 16:04
I also cherry picked this fix onto the next branch. So https://bndtools.ci.cloudbees.com/job/bndtools.next/lastSuccessfulBuild/artifact/build/generated/p2/ contains the fix.

**Comment by flangel** [comment] 2016-01-07 12:52
Hi, thanks for the update. But it didnt solve the issue.

- Using Mars1
- Using Java 1.8
- Using BndTools downloaded here https://bndtools.ci.cloudbees.com/job/bndtools.next/lastSuccessfulBuild/artifact/build/generated/p2/ contains the fix.

Still, when clicking on version number of any bundle in https://dl.bintray.com/bnd/dist/, no bundle is loaded. 

![image](https://cloud.githubusercontent.com/assets/2772980/12170933/c57b80ca-b545-11e5-8fc6-d764c59a6c6a.png)

**Comment by flangel** [comment] 2016-01-07 12:56
Why cannot i reopen this issue?
