### ISSUE TITLE
[Bndtools 4.0.0.REL] Error querying repository Central. java.lang.NullPointerException

### ISSUE THREAD

**Issue by cdealti** [bndtools/bndtools#1893] opened 2018-06-10 10:00 UTC
I'm getting this NPE with Bndtools 4.0.0.REL installed in the latest Eclipse Oxigen on Mac OS Sierra 10.12.6 and Oracle Java SE 8u144.

<img width="876" alt="screen shot 2018-06-10 at 11 47 30" src="https://user-images.githubusercontent.com/1225835/41200406-4d0ea298-6ca4-11e8-88fb-6dc3bf534f16.png">

<img width="704" alt="screen shot 2018-06-10 at 11 58 57" src="https://user-images.githubusercontent.com/1225835/41200495-be1a3ff0-6ca5-11e8-86dc-fd900a97cb52.png">

```
java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

<img width="844" alt="screen shot 2018-06-10 at 11 54 33" src="https://user-images.githubusercontent.com/1225835/41200459-1ca0b974-6ca5-11e8-8704-06720d5e32f9.png">

<img width="1323" alt="screen shot 2018-06-10 at 11 44 12" src="https://user-images.githubusercontent.com/1225835/41200380-f4884a2a-6ca3-11e8-9117-41da4f300774.png">

Eclipse log:

```
!SESSION 2018-06-10 11:42:53.007 -----------------------------------------------
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/cristiano.dealti/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/Users/cristiano.dealti/eclipse-workspace/oxigen/bnd/ -product org.eclipse.epp.package.jee.product -keyring /Users/cristiano.dealti/.eclipse_keyring

!ENTRY bndtools.core 4 0 2018-06-10 11:43:35.010
!MESSAGE Error querying repository Central.
!STACK 0
java.lang.NullPointerException
        at aQute.bnd.repository.maven.provider.MavenBndRepository.list(MavenBndRepository.java:450)
        at bndtools.model.repo.RepositoryTreeContentProvider$1.run(RepositoryTreeContentProvider.java:300)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY bndtools.core 4 0 2018-06-10 11:43:35.030
!MESSAGE Error querying repository Central.
!STACK 0
java.lang.NullPointerException
        at aQute.bnd.repository.maven.provider.MavenBndRepository.list(MavenBndRepository.java:450)
        at bndtools.model.repo.RepositoryTreeContentProvider$1.run(RepositoryTreeContentProvider.java:300)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Bndtools 3.5.0 installed from https://dl.bintray.com/bndtools/bndtools/3.5.0/ work correctly

<img width="1433" alt="screen shot 2018-06-10 at 11 38 30" src="https://user-images.githubusercontent.com/1225835/41200490-7f963996-6ca5-11e8-849a-ad9d7c275997.png">

**Comment by bjhargrave** [comment] 2018-06-18 20:22
I was unable to reproduce this using the latest Bndtools. In looking at the code mentioned in the stacktrace, I am at a loss for how the NPE could even occur.

Can you try again with a fresh Eclipse installation?

**Comment by cdealti** [comment] 2018-06-18 21:44
I've already tried wih a fresh Oxigen install and got the same result. I've opened a related NPE issue for the bnd maven plugins https://github.com/bndtools/bnd/issues/2474. Does it helps? I'm using Oracle Java SE 8u144.

**Comment by bjhargrave** [comment] 2018-06-18 23:13
See https://github.com/bndtools/bnd/issues/2474#issuecomment-398222708 for what is likely also the cause of this issue.

**Comment by bjhargrave** [comment] 2018-06-19 21:17
Closing. See https://github.com/bndtools/bnd/issues/2474.

**Closed by bjhargrave** 2018-06-19 21:17 UTC
