### ISSUE TITLE
Default handler for Launcher-Plugin not found in biz.aQute.launcher

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bndtools#1294] opened 2016-02-24 12:29 UTC
When fooling around with git outside of eclipse and then doing a clean & build of a project, and then trying to run a bndrun file, I get this message _a_ _lot_.

```
Status ERROR: bndtools.core code=0 Error initialising bnd launcher java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
	at aQute.bnd.build.Project.getHandler(Project.java:2456)
	at aQute.bnd.build.Project.getProjectLauncher(Project.java:2404)
	at bndtools.launch.OSGiRunLaunchDelegate.initialiseBndLauncher(OSGiRunLaunchDelegate.java:64)
	at bndtools.launch.AbstractOSGiLaunchDelegate.buildForLaunch(AbstractOSGiLaunchDelegate.java:53)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:855)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

bndtools 3.1.1

I need to restart eclipse to be able to run the bndrun

**Comment by pkriens** [comment] 2016-03-04 17:41
Could you try to create some reproducible steps?

**Comment by fhuberts** [comment] 2016-03-04 19:33
doesn't seem to happen every time, but switching branches around outside of eclipse seems to do it.
then try to run a bdnrun file

**Comment by pkriens** [comment] 2016-03-05 11:27
Without a bit more information this is hard to fix ... So can we close this?

**Comment by fhuberts** [comment] 2016-03-05 11:37
Did you try it?
I not perfectly reproducable but still, it triggers many times.
What more do you want?

**Comment by pkriens** [comment] 2016-03-05 13:16
Well you seem to have a problem that happens regularly, so with your experience you’re capable of finding the set of conditions that trigger much better than me. Since you want this solved I would expect you to be able to spent some time to diagnose it?

Kind regards,

	Peter Kriens

**Comment by fhuberts** [comment] 2016-03-05 13:52
You have all the information I have.
And you know that I will not dig into the code

**Comment by pkriens** [comment] 2016-03-05 15:59
Not requesting to dig into the code. Just the steps to reproduce it consistently.

**Comment by fhuberts** [comment] 2016-03-24 16:19
Maybe this works for you, it just happened to me:

- let eclipse do automatic builds
- build in eclipse: successful build
- switch off eclipse auto builds
- switch to terminal, in workspace root
- git clean -fdx
- git reset --hard
- do a gradle build
- successful gradle build
- git clean -fdx
- git reset --hard
- in eclipse do a project-->clean
- switch on eclipse auto builds
- build in eclipse: successful build
- run a bndrun file --> BOOM

**Comment by timothyjward** [comment] 2016-03-24 18:59
I get this if there is no OSGi framework implementation set, or if it is set and there is no matching framework available in the repositories.

Ensuring that there is a suitable framework set and available has always fixed this for me in the past - however this may be a different issue.

**Closed** 2016-04-29 16:26 UTC

**Comment by dmitryintel** [comment] 2017-07-24 01:50
My 2 cents: I started getting this exception in my maven build AFTER I went into **.bnd** under my home directory and deleted **cache** and **default-ws/cnf/cache** contents:

`IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
    at aQute.bnd.build.Project.getHandler(Project.java:2456) `

Starting eclipse and attempting to run my .bndrun file helped. The **bnd.aQute** version was **3.3.0**.

That's the short story. 

The long sory may not be relevant. The reason I tried deleting caches was that a couple of bundles (A dep. on B) wouldn't resolve after I  messed with their start levels in -runbundles: entry. 

It looked like neither of them started at first, so I tried enforcing the order. That's when I started getting an error that A wouldn't resolve because B was missing. 

Removing the levels again and doing `mvn clean install` didn't make that go away so I attempted deleting bnd caches.

**Comment by arvindn05** [comment] 2017-07-27 20:18
I've had similar issue as well. I manually downloaded the launcher jar into the bnd cache folder and that resolved the problem for me.

See below for the wget command i used.

`
wget -O $HOME/.bnd/default-ws/cnf/cache/3.3.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-3.3.0.jar http://central.maven.org/maven2/biz/aQute/bnd/biz.aQute.launcher/3.3.0/biz.aQute.launcher-3.3.0.jar
`

**Comment by pkriens** [comment] 2017-07-28 08:06
Adding the (a?) launcher to your repositories is a better solution. bnd carries a copy of the launcher but bnd will always look first if your repositories contain a version. That is, there  is no magic in finding the launcher.

Kind regards,

	Peter Kriens

**Comment by bjhargrave** [comment] 2017-08-10 13:41
Whenever the plugins for a  `Workspace` object are first obtained (and `-nobuildincache` is not true), the `CachedFileRepo` is created and the embedded repo files are extracted into `cnf/cache` under a folder for the Bnd version followed by `bnd-cache`. So when you start Eclipse/Bndtools, this happens. If you then go to the command line and delete `cnf/cache`, you hose Eclipse/Bndtools since it has already initialized the plugins for the Workspace and assumes the `CachedFileRepo` is properly populated. The situation can be remedied by either restarting Eclipse/Bndtools or running some part of the command line build to cause a Workspace object (from the same version of Bnd as is being used by Eclipse/Bndtools) to repopulate the `bnd-cache` folder under `cnf/cache`.

**Comment by bjhargrave** [comment] 2017-08-10 14:55
As a followup, some of the Bnd maven plugins for 3.3 did not properly repopulate the `bnd-cache` folder under `cnf/cache`. This has been fixed for 3.4.

**Comment by milendyankov** [comment] 2017-08-11 19:01
I'm getting this error with 3.4.0 plugin when I do `mvn clean install -o` on project that does not have `BndPomRepository` but only `FixedIndexedRepo` which contains entry for `biz.aQute.launcher`  (yes I know how weird this setup is). I'm guessing `clean` deletes the cache and since it's runnig offline (note the `-o`) it can not download it.

**Comment by bjhargrave** [comment] 2017-08-11 19:06
Well if you delete something and you prevent it from being downloaded again, then yes, you will have that thing :-)

**Comment by kriegfrj** [comment] 2018-02-21 10:35
I just hit this error because I had a network connection, but it was a bit too slow and the download of the updated bnd libraries was timing out. That it would fail under such circumstances is completely understandable, but it would be nice if the error message gave a more solid hint as to the root cause.
