### ISSUE TITLE
TimeoutException: "Unable to acquire bndLock" after project import when using Oomph installer on Windows 10

### ISSUE THREAD

**Issue by chriskn** [bndtools/bndtools#1881] opened 2018-04-25 12:28 UTC
## Description ##
After the import of a bnd workspace using the Oomph [ProjectsImportTask](https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.oomph.setup.doc%2Fjavadoc%2Forg%2Feclipse%2Foomph%2Fsetup%2Fprojects%2FProjectsImportTask.html) the bnd classpath build/update leads to multiple java.util.concurrent.TimeoutException. These exceptions can be found in the eclipse log. I attached the logs from my Eclipse at the end of this message. These exceptions stop or at least slow down the build process dramatically. The issue could be reproduced with Eclipse Photon and Oxygen but only reliable on Windows 10 (other windows versions not tested). Furthermore the issue could only be reproduced when the Oomph import task is used. 

- Operation System: Windows 10
- Eclipse:
-- Version: Photon Milestone 6 
-- Build id: 20180315-1217 
- bnd-tools: 3.5.0.REL-20170929-190052-ga0d7a6b	

## HowTo Reproduce ##
I provided an [example oomph setup](https://github.com/chriskn/oomph_bnd_example) which allows me to reproduce the issue on my Windows 10 machine. 

To execute the setup:

1. Download the Oomph Eclipse installer: https://wiki.eclipse.org/Eclipse_Installer
2. Create a local copy of this file: https://github.com/chriskn/oomph_bnd_example/blob/master/oomph_bnd_example/BndTest.setup
3. Start the Oomph installer
![](https://raw.githubusercontent.com/chriskn/oomph_bnd_example/master/oomph_bnd_example/img/startup.jpg)
4. Klick on the menu button in the upper right corner and select "Advanced Mode"
![](https://raw.githubusercontent.com/chriskn/oomph_bnd_example/master/oomph_bnd_example/img/advancedmodeselected.jpg)
5. Select "Eclipse IDE for Java Developers"
6. Select "Latest (Photon)" as Version (Bundle Pool and JRE should be preconfigured)
7. Klick "Next"
8. Drag and Drop the BndTest.setup (the file you created locally) under "Eclipse Projects" or use the green plus button to add the setup
9. Make sure bndTest ist selected in the tree
![](https://raw.githubusercontent.com/chriskn/oomph_bnd_example/master/oomph_bnd_example/img/bndtest.jpg)
10. Klick "Next"
11. Set "Photon" as target platform 
![](https://raw.githubusercontent.com/chriskn/oomph_bnd_example/master/oomph_bnd_example/img/variables.jpg)

After the IDE is installed it should be started. The Exceptions occur after the startup (checkout, import, etc.) during bnd build. You should see the exceptions in the logs of the Eclipse IDE you installed. 

My IDE contains the following features
![](https://raw.githubusercontent.com/chriskn/oomph_bnd_example/master/oomph_bnd_example/img/installation.jpg)

## Logs ##
```!ENTRY org.eclipse.oomph.setup.ui 1 0 2018-04-25 12:55:56.560
!MESSAGE Setup tasks were performed during startup. See 'C:\runtimeoomph\oomph_setup-git-master11\eclipse\configuration\org.eclipse.oomph.setup\setup.log' for details

!ENTRY bndtools.builder 4 0 2018-04-25 12:57:58.403
!MESSAGE Unable to calculate classpath for project example.rcp.app.ui
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 1
	at bndtools.central.Central.bndCall(Central.java:624)
	at bndtools.central.Central.bndCall(Central.java:576)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:235)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:121)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:166)
	at org.bndtools.builder.classpath.BndContainerCompilationParticipant.aboutToBuild(BndContainerCompilationParticipant.java:21)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:607)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY bndtools.builder 2 0 2018-04-25 12:59:58.706
!MESSAGE Unable to build project example.rcp.app.ui
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:624)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:119)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY bndtools.builder 4 0 2018-04-25 13:01:58.824
!MESSAGE Unable to calculate classpath for project example.rcp.headless
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:624)
	at bndtools.central.Central.bndCall(Central.java:576)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:235)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:121)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:166)
	at org.bndtools.builder.classpath.BndContainerCompilationParticipant.aboutToBuild(BndContainerCompilationParticipant.java:21)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:607)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY bndtools.builder 2 0 2018-04-25 13:03:58.957
!MESSAGE Unable to build project example.rcp.headless
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:624)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:119)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY bndtools.builder 4 0 2018-04-25 13:05:59.066
!MESSAGE Unable to calculate classpath for project example.rcp.ui
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:624)
	at bndtools.central.Central.bndCall(Central.java:576)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:235)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:121)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:166)
	at org.bndtools.builder.classpath.BndContainerCompilationParticipant.aboutToBuild(BndContainerCompilationParticipant.java:21)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:607)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY bndtools.builder 2 0 2018-04-25 13:07:59.226
!MESSAGE Unable to build project example.rcp.ui
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:624)
	at org.bndtools.builder.BndtoolsBuilder.build(BndtoolsBuilder.java:119)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:790)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:211)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:310)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:362)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:401)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$5.run(SetupTaskPerformer.java:3369)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)```

**Comment by bjhargrave** [comment] 2018-04-25 13:10
It looks like one job is not releasing the bndCall lock for over 120 seconds which is a long time. The code also will restart the 120 second timeout if any thread holding the bndCall lock releases it. 

I would suggest turning off Build Automatically during a workspace import. After the import is complete, then start building the workspace.

But the stack traces all seem to show the oomph setup task is explicitly calling build which does not seem like a great idea either. I would think oomph should just import the projects and then let eclipse build the project naturally.

**Comment by chriskn** [comment] 2018-04-25 14:14
The way a project is imported and build can't be configured using the Oomph ProjectsImportTask. You can only point on a directory. I assume the type of project/workspace should be detected automatically by the Eclipse [Smarter import framework](https://wiki.eclipse.org/E4/UI/Smart_Import).
See also issue [1400](https://github.com/bndtools/bndtools/issues/1400)

At least as far I understand it's propuse, it could be used to detect the bnd nature and import/setup the workspace accordingly.

**Comment by chriskn** [comment] 2018-05-07 09:33
The issue is also reproducable on linux x64 (Kubuntu 17.10) but you have to run the same setup a second time.
## Howto Reproduce on linux: ##
1. First try ran successful, bnd workspace green, all good
2. **Second try ran into the linked known issue "Unable to acquire bndLock"**
3. before 3rd try, deleted oomph setup cache at <HOME_DIR>/.eclipse/org.eclipse.oomph.setup/ and Oomph eclipse installer (deleted and unpacked again) => again ran into known issue "Unable to acquire bndLock"
4. before the 4th try, I additionally deleted the installation folder of the previous installations => again ran into known issue "Unable to acquire bndLock"

**Comment by bjhargrave** [comment] 2018-05-07 14:10
Please try the latest bndtools from cloudbees and reproduce. Then attach the log entries with the timeout exceptions. Thanks,

**Comment by bjhargrave** [comment] 2018-05-07 19:57
`bndCall` is used in 2 main ways by Bndtools.

1) To build or compute the classpath container contents when building.
2) Refesh the WorkspaceRepository or list the repositories.

**Comment by chriskn** [comment] 2018-05-08 06:57
With version 4.0.0.201805071404 I get this

```
!ENTRY bndtools.core 4 0 2018-05-08 08:49:04.369
!MESSAGE Error loading repositories: Unable to acquire bndLock[java.util.concurrent.locks.ReentrantLock@5ae30764[Locked by thread Worker-26: Adjusting classpaths for new projects]]; has waiters: 0
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock[java.util.concurrent.locks.ReentrantLock@5ae30764[Locked by thread Worker-26: Adjusting classpaths for new projects]]; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:659)
	at bndtools.central.Central.bndCall(Central.java:613)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:30)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:25)
	at org.bndtools.builder.classpath.BndContainerSourceManager.getSourceBundle(BndContainerSourceManager.java:178)
	at org.bndtools.builder.classpath.BndContainerSourceManager.loadAttachedSources(BndContainerSourceManager.java:124)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:230)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:79)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3169)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3075)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3113)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2109)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3613)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3124)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3288)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2365)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.refreshReferences(ExternalFoldersManager.java:409)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2072)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:476)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:269)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:371)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1546)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1088)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1107)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:288)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl$1.run(ProjectsImportTaskImpl.java:384)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2311)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.importProjects(ProjectsImportTaskImpl.java:372)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.perform(ProjectsImportTaskImpl.java:295)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3332)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3275)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4502)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4496)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4494)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3266)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3241)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3141)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.AssertionError: This throwable holds the caller stacktrace of the bndLock owner
	at bndtools.central.Central.bndCall(Central.java:643)
	at bndtools.central.Central.bndCall(Central.java:613)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:224)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:105)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:151)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:57)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	... 1 more

!ENTRY bndtools.core 4 0 2018-05-08 08:51:04.507
!MESSAGE Error loading repositories: Unable to acquire bndLock[java.util.concurrent.locks.ReentrantLock@5ae30764[Locked by thread Worker-26: Adjusting classpaths for new projects]]; has waiters: 0
!STACK 0
java.util.concurrent.TimeoutException: Unable to acquire bndLock[java.util.concurrent.locks.ReentrantLock@5ae30764[Locked by thread Worker-26: Adjusting classpaths for new projects]]; has waiters: 0
	at bndtools.central.Central.bndCall(Central.java:659)
	at bndtools.central.Central.bndCall(Central.java:613)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:30)
	at bndtools.central.RepositoryUtils.listRepositories(RepositoryUtils.java:25)
	at org.bndtools.builder.classpath.BndContainerSourceManager.getSourceBundle(BndContainerSourceManager.java:178)
	at org.bndtools.builder.classpath.BndContainerSourceManager.loadAttachedSources(BndContainerSourceManager.java:124)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:230)
	at org.bndtools.builder.classpath.BndContainerInitializer.initialize(BndContainerInitializer.java:79)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3169)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3075)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3113)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2109)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3613)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3124)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3288)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2365)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.refreshReferences(ExternalFoldersManager.java:409)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2072)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:476)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:269)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:371)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1546)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1088)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1107)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:288)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl$1.run(ProjectsImportTaskImpl.java:384)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2311)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.importProjects(ProjectsImportTaskImpl.java:372)
	at org.eclipse.oomph.setup.projects.impl.ProjectsImportTaskImpl.perform(ProjectsImportTaskImpl.java:295)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3332)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3275)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4502)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4496)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4494)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3266)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3241)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3141)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.AssertionError: This throwable holds the caller stacktrace of the bndLock owner
	at bndtools.central.Central.bndCall(Central.java:643)
	at bndtools.central.Central.bndCall(Central.java:613)
	at org.bndtools.builder.classpath.BndContainerInitializer$Updater.updateClasspathContainer(BndContainerInitializer.java:224)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:105)
	at org.bndtools.builder.classpath.BndContainerInitializer.requestClasspathContainerUpdate(BndContainerInitializer.java:151)
	at org.bndtools.builder.jobs.newproject.AdjustClasspathsForNewProjectJob.runInWorkspace(AdjustClasspathsForNewProjectJob.java:57)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	... 1 more

```

**Comment by pkriens** [comment] 2018-05-08 07:51
![image](https://user-images.githubusercontent.com/200494/39744693-6c9872d8-52a5-11e8-8d7d-b2b9f9f7d34a.png)

**Comment by pkriens** [comment] 2018-05-08 07:55
I wonder if this is caused by a deadlock between the repositories update and the builder. I will see if I can reproduce this without Oomph. 

Also:
![image](https://user-images.githubusercontent.com/200494/39744889-fd5821f6-52a5-11e8-97a7-d87ff441615f.png)

**Comment by pkriens** [comment] 2018-05-08 08:16
I am trying to recreate the problem in a standalone workspace. However, some problems:

* The build.bnd file defines a JPM Repository that is no longer supported
* The P2 repos are supposed to be in ~/www... but I do not see them on my system
* Trying the actual URLs to the servers gives me SSL errors

I think it would be best if you first try this with a working workspace (there are some on the OSGi enRoute Github site. E.g. this is an empty workspace: https://github.com/osgi/enroute.workspace

**Comment by chriskn** [comment] 2018-05-08 08:26
I updated my test setup accordingly. With https://github.com/osgi/enroute.workspace I don't get error. But this is in my opinion not a valid test worspace, because it does not contain any projects.

**Comment by pkriens** [comment] 2018-05-08 10:34
True, but at least that makes it more clear what to look for since the base all works. Could you also try https://github.com/osgi/osgi.enroute.examples ? That is a more complete workspace. If you explain how to use different workspaces I can also take a look

**Comment by chriskn** [comment] 2018-05-08 12:08
You can use different workspaces by changing the git url in the GitCloneTask. Have a look at this [commit](https://github.com/chriskn/oomph_bnd_example/commit/30d55a50e083eb23524189d3b44361bed9ebb50f). I tryed it and got the same error.

**Comment by chriskn** [comment] 2018-05-08 14:38
We were able to get it working by defining two separated import tasks. The first one only imports the cnf folder, the second one all other projects. No error anymore in the eclipse logs.

**Comment by bjhargrave** [comment] 2018-05-10 13:29
I am going to close this issue. The cnf project must be imported first before any other projects can be built.

**Closed by bjhargrave** 2018-05-10 13:29 UTC
