### ISSUE TITLE
Private-Package adds Import-Package statement?

### ISSUE THREAD

**Issue by ulfnielsen** [bndtools/bndtools#1000] opened 2015-01-13 19:31 UTC
I have a bundle with 
*Private-Package: com.acme.private*
and the resulting jar contains that as well as an entry for that package in *Import-Package* section. 

This cause Resolve on the run file to fail resolving that package it seems. I checked a previous version of the build jar and it does not contain the import-package entry for that package.

I'm using 2.4.1.RC3-20150112-223453-ga65dd95

**Comment by bjhargrave** [comment] 2015-01-13 19:33
Does this work as you expect on 2.4.0.REL? (I am wondering if this is a regression for 2.4.1.)

**Comment by ulfnielsen** [comment] 2015-01-13 19:36
Sorry haven't tried again on the release. But it worked last week when I was on a build pre-2.4.0. I just installed the rc to get some of the speed improvement on resolve and noticed this, haven't changed anything else so I'm fairly sure it's a regression in 2.4.1.

**Comment by bjhargrave** [comment] 2015-01-13 19:39
OK, we need a test to demonstrate the problem. Best would be a PR (on [bnd](https://github.com/bndtools/bnd) master) with a new test method in biz.aQute.bndlib.tests (see https://github.com/bndtools/bnd/commit/e7383fb1c8948fc1c48353d946e1c3ecb393abd8 for an example). Next best is a workspace which simply demonstrates the problem. Thanks.

**Comment by bjhargrave** [comment] 2015-01-13 20:08
@pkriens Can you look at this to see if you think this is a 2.4.1 regression?

**Comment by bjhargrave** [comment] 2015-01-13 20:09
And @ulfnielsen, congratulations on filing issue #1000! :-)

**Comment by ulfnielsen** [comment] 2015-01-14 07:01
He, didn't even notice. But I have narrowed the issue down a bit. It only seems to happen when I have a -wab directive. I'll try to create a minimal project to test

**Comment by ulfnielsen** [comment] 2015-01-14 08:28
I've created a minimal workspace showing showing the issue. If you remove the  *-wab: www=www* line in *test/bnd.bnd* you can successfully Resolve in launch.bndrun. If it's present it fails.

The workspace is here: https://github.com/ulfnielsen/i1000

**Comment by bjhargrave** [comment] 2015-01-14 15:32
OK, I can confirm this is definitely a regression caused by https://github.com/bndtools/bnd/commit/e7383fb1c8948fc1c48353d946e1c3ecb393abd8. If you build the test repo (`gradle :test:jar`) using bnd 2.4.0 (I edited the gradle.properties file to set `bnd_jar=https://bndtools.ci.cloudbees.com/job/bnd.master/470/artifact/dist/bundles/biz.aQute.bnd.gradle/biz.aQute.bnd.gradle-2.4.0.jar`), then the manifest is correct:

    Export-Package: test2;version="0.0.0"
    Private-Package: test

However, if you build with 2.4.1.RC3, the manifest is incorrect:

    Export-Package: test2;version="1.0.0"
    Import-Package: test,test2;version="[1.0,2)"
    Private-Package: test

I also reverted https://github.com/bndtools/bnd/commit/e7383fb1c8948fc1c48353d946e1c3ecb393abd8 locally and building without that commit also creates a correct manifest.

@pkriens I need to you to look at this to resolve before we can release 2.4.1.

**Comment by bjhargrave** [comment] 2015-01-14 15:42
> then the manifest is correct:
> 
> Export-Package: test2;version="0.0.0"
> Private-Package: test

Well the 2.4.0 generated manifest is not entirely correct. test2 has a packageinfo for version 1.0.0 which is not included on the export. At least 2.4.1 got that right!

**Comment by bjhargrave** [comment] 2015-01-14 16:30
It appears that cherry-picking the fix from master into next caused the regression. Building the test project with bnd master (`bnd_jar=https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz.aQute.bnd.gradle/biz.aQute.bnd.gradle-latest.jar`) creates the proper manifest:

    Export-Package: test2;version="1.0.0"
    Private-Package: test

So it seems the fix for bndtools/bnd#708 depends on previous changes post 2.4.0.REL and cannot be cherry-picked into next for a maintenance release.

**Comment by bjhargrave** [comment] 2015-01-14 19:41
Fixed by https://github.com/bndtools/bnd/issues/777.

**Closed by bjhargrave** 2015-01-14 19:41 UTC
