### ISSUE TITLE
Generated jar file name is not aligned to options set in bnd.bnd file 

### ISSUE THREAD

**Issue by nport** [bndtools/bndtools#1124] opened 2015-06-11 14:10 UTC
Eclipse platform: Windows 7

In the bnd.bnd file there are the following two lines:

<code>Bundle-Version: 2.0.1</code>
<code>-outputmask: ${@bsn}-${version;===S;${@version}}.jar</code>

With this directives bnd generates correctly the file <code>target/<projectname>-2.0.1.jar</code>

If I remove the -outputmask line, bndtools correctly deletes the file above and creates this new one:
<code>target/<projectname>.jar</code>

Then if the <code>-outputmask</code> directive is added again, I would expect the filename to be replaced with the initial one, but what happens is that:
- A <code>target/<projectname>-2.0.1.jar</code> appears in the Eclipse workspace
- After less than 1 second it disappears.

The only jar file that remains in the target dir is <code><projectname>.jar</code>

A clean of the workspace (Menu Projects-> Clean ...) replaces the wrong filename with the correct one.

**Comment by bjhargrave** [comment] 2017-09-26 20:40
Works for me in latest 3.5 builds on my mac. For windows user, this may be caused by the file lock issue which is being worked by another issue. So closing this issue.

**Closed by bjhargrave** 2017-09-26 20:40 UTC
