### ISSUE TITLE
Unused NLS message in bndtools.editor.project.messages

### ISSUE THREAD

**Issue by rherrmann** [bndtools/bndtools#1631] opened 2017-01-23 13:54 UTC
When running Bndtools from within the IDE, I see this message written to `System.err`:

> Warning: NLS unused message: RunBundlesPart_warningHover in: bndtools.editor.project.messages

**Comment by seanbright** [comment] 2017-05-17 21:11
Duplicate of #1595

**Closed by seanbright** 2017-05-17 21:11 UTC
