### ISSUE TITLE
Project does not always build in Eclipse even though its build path is correct.

### ISSUE THREAD

**Issue by m4rr5** [bndtools/bndtools#937] opened 2014-11-05 20:11 UTC
Say you create three projects in a workspace:

 * pa - a project with build dependencies on pb and pc.a, and a class that uses a type A from pc.a
 * pb - a project with a build dependency on pc.b, and a class that uses a type B from pc.b
 * pc - a project with sub bundles, pc.a and pc.b

If you create the projects in this order, particularly with the build dependencies in pa in that order, Eclipse refuses to build pa because of the following error:

Access restriction: The type A is not accessible due to restriction on required project pc

If you now reverse the build order in pa to pc.a and then pb, it works.

In gradle, it works in all cases.

The problem seems to originate from the fact that Bndtools converts bundle dependencies into project dependencies with access restrictions. Furthermore, it seems that these project dependencies are transitive and that the first dependency "shadows" any following ones.

To reproduce, these are the exact projects and their files (I left out cnf, it is irrelevant to this setup, just generate it):

	pa/
		src/pa/UsesA.java
			package pa;
			import pc.a.A;
			public class UsesA {
				A a;
			}
		bnd.bnd
			-buildpath:  \
				pb;version=latest,\
				pc.a;version=latest
	pb/
		src/pb/UsesB.java
			package pb;
			import pc.b.B;
			public class UsesB {
				B b;
			}
		bnd.bnd
			-buildpath:  \
				pc.b;version=latest
	pc/
		src/pc/a/A.java
			package pc.a;
			public interface A {}
		src/pc/b/B.java
			package pc.b;
			public interface B {}
		a.bnd
			Export-Package: pc.a
		b.bnd
			Export-Package: pc.b
		bnd.bnd
			-sub: *.bnd

**Comment by derheld42** [comment] 2015-01-15 06:56
wow.. this is weird... I'm attempting to see if this is related to #999 and it's not, #999 deals with version=file references. However this is in the same area of code so I thought I'd take a swing at it.

I noticed this.. if you remove the pb;version=latest from the pa buildpath, it builds fine.
If you add it back, it doesn't work.

In BndContainerInitializer, it looks like the access rules are getting created correctly for the pc project. (i.e. you remove pb and it works fine). Somehow the pb reference -- which has a ** NOT ACCESSIBLE access rules, breaks the connection to pc. weird.

I started to fix it by not adding a project reference when there wasn't an export.. this kinda worked (although would have other negative sideeffects), and allowed things to build, until I added an export to pb, which then caused it to break again.

I added some print outs to see if the access rules are wrong somehow... here's what they are -- which are correct (from my understanding of how this stuff works) ... 

SUMMARY: project = pc
--- /cnf/buildrepo/osgi.core/osgi.core-4.0.1.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.core]
--- /home/user/.bnd/cache/https%3A%2F%2Fraw.githubusercontent.com%2Fbndtools%2Fbundle-hub%2Fmaster%2Fosgi.cmpn/osgi.cmpn-5.0.0.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.cmpn,version=5.0.0]

SUMMARY: project = pb
--- /cnf/buildrepo/osgi.core/osgi.core-4.0.1.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.core]
--- /home/user/.bnd/cache/https%3A%2F%2Fraw.githubusercontent.com%2Fbndtools%2Fbundle-hub%2Fmaster%2Fosgi.cmpn/osgi.cmpn-5.0.0.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.cmpn,version=5.0.0]
--- /pc[CPE_PROJECT][K_SOURCE][isExported:true][AccessRuleSet {pattern=pc/b/* (ACCESSIBLE), pattern=** (NON ACCESSIBLE)} [classpath entry: pc]][combine access rules:false][attributes:bsn=pc.b.jar]

SUMMARY: project = pa
--- /cnf/buildrepo/osgi.core/osgi.core-4.0.1.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.core]
--- /home/user/.bnd/cache/https%3A%2F%2Fraw.githubusercontent.com%2Fbndtools%2Fbundle-hub%2Fmaster%2Fosgi.cmpn/osgi.cmpn-5.0.0.jar[CPE_LIBRARY][K_BINARY][isExported:false][attributes:bsn=osgi.cmpn,version=5.0.0]
--- /pb[CPE_PROJECT][K_SOURCE][isExported:true][AccessRuleSet {pattern=pb/* (ACCESSIBLE), pattern=** (NON ACCESSIBLE)} [classpath entry: pb]][combine access rules:false][attributes:bsn=pb.jar]
--- /pc[CPE_PROJECT][K_SOURCE][isExported:true][AccessRuleSet {pattern=pc/a/* (ACCESSIBLE), pattern=** (NON ACCESSIBLE)} [classpath entry: pc]][combine access rules:false][attributes:bsn=pc.a.jar]


However, this use case caused to test a bit more.. I think my approach isn't quite right. I have an idea....

**Comment by derheld42** [comment] 2015-01-15 07:03
I got it (at least a solution for the access issue). I'll update the pull request on #999 since I think this might solve broader issues.

**Comment by derheld42** [comment] 2015-01-17 04:52
I'm closing this out. I retested it with the fix in #999 and I couldn't reproduce it after. We can reopen if you're seeing something different.

**Comment by derheld42** [comment] 2015-01-17 07:30
#999 missed a case. Reopening until I solve it.

**Comment by derheld42** [comment] 2015-01-25 06:01
I believe #1003 resolves this issue. In my testing, it works. Please close out if it does.

To try the new access rules, add to cnf/build.bnd:
eclipse.newaccessrules: true

**Closed** 2015-02-16 22:04 UTC
