### ISSUE TITLE
Open the "source" tab by default results in empty "run" tab

### ISSUE THREAD

**Issue by joerg-wille** [bndtools/bndtools#1740] opened 2017-07-03 22:47 UTC
Using 3.4.0-RC2
If checked "Open the source tab by default" in Bndtools settings any opened bndrun file opens directly with presenting the source tab as expected.
When you now switch to the run tab (without changing and saving the bndrun file) you get an empty run tab:
![source-first](https://user-images.githubusercontent.com/12610094/27809681-34a02aa6-6052-11e7-8fe0-90242973396f.jpeg)

**Comment by bjhargrave** [comment] 2017-07-05 12:17
Can you look at this @gamerson ?

**Comment by gamerson** [comment] 2017-07-05 13:43
hey @joerg-wille 

I am not able to reproduce this issue with my test workspaces.  So a couple of things?

1) is there any errors in the error log ( Window > Show View > Other... > Error Log )
2) do you have spaces in your path to your workspace (a bug in bnd was recently fixed for this)
3) Could you provide us with a sample workspace to try to reproduce the problem?

**Comment by bjhargrave** [comment] 2018-01-19 17:46
Closing as unreproducible.

**Closed by bjhargrave** 2018-01-19 17:46 UTC
